### ISSUE TITLE
provide command to go to the first highlight

### ISSUE THREAD

**Issue by tjx666** [zardoy/vscode-highlight-utils#3]
So I can use this command to go to import statement

**Comment by zardoy** [comment]
```json
// keybindings.json
{
    "key": "...",
    "command": "highlightUtils.goToHighlightedLocations",
    "args": {
        "at": 0
    }
}
```

But I must admit it doesn't work with imported react components with closing elements, so https://github.com/zardoy/typescript-vscode-plugins/issues/111 might be more useful for you.

**Comment by tjx666** [comment]
@zardoy this way only make the cursor to the first highlight, but not jump to that position

**Comment by zardoy** [comment]
> but not jump to that position

What do you mean by jumping to that position?

**Comment by tjx666** [comment]
@zardoy https://github.com/zardoy/vscode-highlight-utils/pull/4

**Comment by tjx666** [comment]
I need to scroll to the location manully...

https://user-images.githubusercontent.com/41773861/230954296-07eafcf3-3c25-441d-adcd-34db571a4650.mov
